package com.gzsll.hupu.support.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table BOARD.
 */
public class Board implements Serializable {

    private Long id;
    private Long BoardId;
    private String CategoryName;
    private Long CategoryId;
    private String BoardName;
    private String BoardIcon;
    private Long GroupId;
    private Integer BoardIndex;

    public Board() {
    }

    public Board(Long id) {
        this.id = id;
    }

    public Board(Long id, Long BoardId, String CategoryName, Long CategoryId, String BoardName, String BoardIcon, Long GroupId, Integer BoardIndex) {
        this.id = id;
        this.BoardId = BoardId;
        this.CategoryName = CategoryName;
        this.CategoryId = CategoryId;
        this.BoardName = BoardName;
        this.BoardIcon = BoardIcon;
        this.GroupId = GroupId;
        this.BoardIndex = BoardIndex;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBoardId() {
        return BoardId;
    }

    public void setBoardId(Long BoardId) {
        this.BoardId = BoardId;
    }

    public String getCategoryName() {
        return CategoryName;
    }

    public void setCategoryName(String CategoryName) {
        this.CategoryName = CategoryName;
    }

    public Long getCategoryId() {
        return CategoryId;
    }

    public void setCategoryId(Long CategoryId) {
        this.CategoryId = CategoryId;
    }

    public String getBoardName() {
        return BoardName;
    }

    public void setBoardName(String BoardName) {
        this.BoardName = BoardName;
    }

    public String getBoardIcon() {
        return BoardIcon;
    }

    public void setBoardIcon(String BoardIcon) {
        this.BoardIcon = BoardIcon;
    }

    public Long getGroupId() {
        return GroupId;
    }

    public void setGroupId(Long GroupId) {
        this.GroupId = GroupId;
    }

    public Integer getBoardIndex() {
        return BoardIndex;
    }

    public void setBoardIndex(Integer BoardIndex) {
        this.BoardIndex = BoardIndex;
    }

}
