package com.gzsll.hupu.support.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table DBCOVER.
 */
public class DBCover {

    private Long id;
    private String urlSmall;
    private Integer height;
    private String url;
    private Integer width;

    public DBCover() {
    }

    public DBCover(Long id) {
        this.id = id;
    }

    public DBCover(Long id, String urlSmall, Integer height, String url, Integer width) {
        this.id = id;
        this.urlSmall = urlSmall;
        this.height = height;
        this.url = url;
        this.width = width;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrlSmall() {
        return urlSmall;
    }

    public void setUrlSmall(String urlSmall) {
        this.urlSmall = urlSmall;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

}
