package com.gzsll.hupu.support.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table DBGROUPS.
 */
public class DBGroups {

    private Long id;
    private String groupName;
    private Long serverId;

    public DBGroups() {
    }

    public DBGroups(Long id) {
        this.id = id;
    }

    public DBGroups(Long id, String groupName, Long serverId) {
        this.id = id;
        this.groupName = groupName;
        this.serverId = serverId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

}
