package com.gzsll.hupu.support.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table DBTHREAD_REPLY_ITEM.
 */
public class DBThreadReplyItem {

    private Long id;
    private Long serverId;
    private Long pid;
    private String createAt;
    private Integer lights;
    private Integer floor;
    private Long groupThreadId;
    private Long userId;
    private String content;
    private Boolean isHot;

    public DBThreadReplyItem() {
    }

    public DBThreadReplyItem(Long id) {
        this.id = id;
    }

    public DBThreadReplyItem(Long id, Long serverId, Long pid, String createAt, Integer lights, Integer floor, Long groupThreadId, Long userId, String content, Boolean isHot) {
        this.id = id;
        this.serverId = serverId;
        this.pid = pid;
        this.createAt = createAt;
        this.lights = lights;
        this.floor = floor;
        this.groupThreadId = groupThreadId;
        this.userId = userId;
        this.content = content;
        this.isHot = isHot;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public Long getPid() {
        return pid;
    }

    public void setPid(Long pid) {
        this.pid = pid;
    }

    public String getCreateAt() {
        return createAt;
    }

    public void setCreateAt(String createAt) {
        this.createAt = createAt;
    }

    public Integer getLights() {
        return lights;
    }

    public void setLights(Integer lights) {
        this.lights = lights;
    }

    public Integer getFloor() {
        return floor;
    }

    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    public Long getGroupThreadId() {
        return groupThreadId;
    }

    public void setGroupThreadId(Long groupThreadId) {
        this.groupThreadId = groupThreadId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Boolean getIsHot() {
        return isHot;
    }

    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

}
