package com.gzsll.hupu.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table IMAGE_CACHE.
 */
public class ImageCache {

    private Long id;
    private String url;
    private String path;

    public ImageCache() {
    }

    public ImageCache(Long id) {
        this.id = id;
    }

    public ImageCache(Long id, String url, String path) {
        this.id = id;
        this.url = url;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }
}
