package com.gzsll.hupu.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table THREAD.
 */
public class Thread {

    private String tid;
    private String title;
    private String puid;
    private String fid;
    private String replies;
    private String userName;
    private String time;
    private String forumName;
    private Integer lightReply;
    private Integer type;
    private Forum forum;

    public Thread() {
    }

    public Thread(String tid, String title, String puid, String fid, String replies,
                  String userName, String time, String forumName, Integer lightReply, Integer type) {
        this.tid = tid;
        this.title = title;
        this.puid = puid;
        this.fid = fid;
        this.replies = replies;
        this.userName = userName;
        this.time = time;
        this.forumName = forumName;
        this.lightReply = lightReply;
        this.type = type;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPuid() {
        return puid;
    }

    public void setPuid(String puid) {
        this.puid = puid;
    }

    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getReplies() {
        return replies;
    }

    public void setReplies(String replies) {
        this.replies = replies;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getForumName() {
        return forumName;
    }

    public void setForumName(String forumName) {
        this.forumName = forumName;
    }

    public Integer getLightReply() {
        return lightReply;
    }

    public void setLightReply(Integer lightReply) {
        this.lightReply = lightReply;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Forum getForum() {
        return forum;
    }

    public void setForum(Forum forum) {
        this.forum = forum;
    }
}
