package com.gzsll.hupu.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.gzsll.hupu.bean.BaseError;

/**
 * Entity mapped to table THREAD_INFO.
 */
public class ThreadInfo {

    private String tid;
    private String pid;
    private Integer page;
    private String nopic;
    private Integer postAuthorPuid;
    private String time;
    private String userImg;
    private String author_puid;
    private String username;
    private String fid;
    private String visits;
    private String recommend_num;
    private String via;
    private String update_info;
    private String content;
    private String title;
    private Integer totalPage;
    private String forumName;
    private Forum forum;
    private BaseError error;

    public ThreadInfo() {
    }

    public ThreadInfo(String tid, String pid, Integer page, String nopic, Integer postAuthorPuid,
                      String time, String userImg, String author_puid, String username, String fid, String visits,
                      String recommend_num, String via, String update_info, String content, String title,
                      Integer totalPage, String forumName) {
        this.tid = tid;
        this.pid = pid;
        this.page = page;
        this.nopic = nopic;
        this.postAuthorPuid = postAuthorPuid;
        this.time = time;
        this.userImg = userImg;
        this.author_puid = author_puid;
        this.username = username;
        this.fid = fid;
        this.visits = visits;
        this.recommend_num = recommend_num;
        this.via = via;
        this.update_info = update_info;
        this.content = content;
        this.title = title;
        this.totalPage = totalPage;
        this.forumName = forumName;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public String getNopic() {
        return nopic;
    }

    public void setNopic(String nopic) {
        this.nopic = nopic;
    }

    public Integer getPostAuthorPuid() {
        return postAuthorPuid;
    }

    public void setPostAuthorPuid(Integer postAuthorPuid) {
        this.postAuthorPuid = postAuthorPuid;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getUserImg() {
        return userImg;
    }

    public void setUserImg(String userImg) {
        this.userImg = userImg;
    }

    public String getAuthor_puid() {
        return author_puid;
    }

    public void setAuthor_puid(String author_puid) {
        this.author_puid = author_puid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getVisits() {
        return visits;
    }

    public void setVisits(String visits) {
        this.visits = visits;
    }

    public String getRecommend_num() {
        return recommend_num;
    }

    public void setRecommend_num(String recommend_num) {
        this.recommend_num = recommend_num;
    }

    public String getVia() {
        return via;
    }

    public void setVia(String via) {
        this.via = via;
    }

    public String getUpdate_info() {
        return update_info;
    }

    public void setUpdate_info(String update_info) {
        this.update_info = update_info;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getTotalPage() {
        return totalPage;
    }

    public void setTotalPage(Integer totalPage) {
        this.totalPage = totalPage;
    }

    public String getForumName() {
        return forumName;
    }

    public void setForumName(String forumName) {
        this.forumName = forumName;
    }

    public Forum getForum() {
        return forum;
    }

    public void setForum(Forum forum) {
        this.forum = forum;
    }

    public BaseError getError() {
        return error;
    }

    public void setError(BaseError error) {
        this.error = error;
    }
}
