package com.hupu.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.hupu.db.Board;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BOARD.
*/
public class BoardDao extends AbstractDao<Board, Long> {

    public static final String TABLENAME = "BOARD";

    /**
     * Properties of entity Board.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BoardId = new Property(1, Long.class, "BoardId", false, "BOARD_ID");
        public final static Property CategoryName = new Property(2, String.class, "CategoryName", false, "CATEGORY_NAME");
        public final static Property CategoryId = new Property(3, Long.class, "CategoryId", false, "CATEGORY_ID");
        public final static Property BoardName = new Property(4, String.class, "BoardName", false, "BOARD_NAME");
        public final static Property BoardIcon = new Property(5, String.class, "BoardIcon", false, "BOARD_ICON");
        public final static Property GroupId = new Property(6, Long.class, "GroupId", false, "GROUP_ID");
        public final static Property BoardIndex = new Property(7, Integer.class, "BoardIndex", false, "BOARD_INDEX");
    };


    public BoardDao(DaoConfig config) {
        super(config);
    }
    
    public BoardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BOARD' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BOARD_ID' INTEGER," + // 1: BoardId
                "'CATEGORY_NAME' TEXT," + // 2: CategoryName
                "'CATEGORY_ID' INTEGER," + // 3: CategoryId
                "'BOARD_NAME' TEXT," + // 4: BoardName
                "'BOARD_ICON' TEXT," + // 5: BoardIcon
                "'GROUP_ID' INTEGER," + // 6: GroupId
                "'BOARD_INDEX' INTEGER);"); // 7: BoardIndex
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BOARD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Board entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long BoardId = entity.getBoardId();
        if (BoardId != null) {
            stmt.bindLong(2, BoardId);
        }
 
        String CategoryName = entity.getCategoryName();
        if (CategoryName != null) {
            stmt.bindString(3, CategoryName);
        }
 
        Long CategoryId = entity.getCategoryId();
        if (CategoryId != null) {
            stmt.bindLong(4, CategoryId);
        }
 
        String BoardName = entity.getBoardName();
        if (BoardName != null) {
            stmt.bindString(5, BoardName);
        }
 
        String BoardIcon = entity.getBoardIcon();
        if (BoardIcon != null) {
            stmt.bindString(6, BoardIcon);
        }
 
        Long GroupId = entity.getGroupId();
        if (GroupId != null) {
            stmt.bindLong(7, GroupId);
        }
 
        Integer BoardIndex = entity.getBoardIndex();
        if (BoardIndex != null) {
            stmt.bindLong(8, BoardIndex);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Board readEntity(Cursor cursor, int offset) {
        Board entity = new Board( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // BoardId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // CategoryName
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // CategoryId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // BoardName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // BoardIcon
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // GroupId
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // BoardIndex
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Board entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBoardId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCategoryName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCategoryId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setBoardName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBoardIcon(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGroupId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setBoardIndex(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Board entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Board entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
