package com.gzsll.hupu.support.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DBMINI_REPLY_LIST_ITEM.
 */
public class DBMiniReplyListItem {

    private Long id;
    private Long serverId;
    private Long pid;
    private String formatTime;
    private Long groupThreadId;
    private Long userId;
    private String content;
    private Long parentReplyId;

    public DBMiniReplyListItem() {
    }

    public DBMiniReplyListItem(Long id) {
        this.id = id;
    }

    public DBMiniReplyListItem(Long id, Long serverId, Long pid, String formatTime, Long groupThreadId, Long userId, String content, Long parentReplyId) {
        this.id = id;
        this.serverId = serverId;
        this.pid = pid;
        this.formatTime = formatTime;
        this.groupThreadId = groupThreadId;
        this.userId = userId;
        this.content = content;
        this.parentReplyId = parentReplyId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public Long getPid() {
        return pid;
    }

    public void setPid(Long pid) {
        this.pid = pid;
    }

    public String getFormatTime() {
        return formatTime;
    }

    public void setFormatTime(String formatTime) {
        this.formatTime = formatTime;
    }

    public Long getGroupThreadId() {
        return groupThreadId;
    }

    public void setGroupThreadId(Long groupThreadId) {
        this.groupThreadId = groupThreadId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getParentReplyId() {
        return parentReplyId;
    }

    public void setParentReplyId(Long parentReplyId) {
        this.parentReplyId = parentReplyId;
    }

}
